import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Primer Nivel",
      items: ["primer-nivel/materia1", "primer-nivel/materia2"],
    },
    {
      type: "category",
      label: "Segundo Nivel",
      items: ["segundo-nivel/materia3", "segundo-nivel/materia4"],
    },
    {
      type: "category",
      label: "Tercer Nivel",
      items: ["tercer-nivel/materia5", "tercer-nivel/materia6"],
    },
  ],
};

export default sidebars;
